### ISSUE TITLE
requirements.txt supported for train but not deploy?

### ISSUE THREAD

**Issue by athewsey** [aws/sagemaker-mxnet-container#143]
I'm installing GluonCV via a requirements.txt file in my `source_dir`, which seems to be working fine for my training job but then ignored when the container starts up for inference: leading to `ModuleNotFoundError`.

I guess I could install the dependency inline in the script with something like the below, but then the requirements.txt functionality is kind of inconsistent right? I could have just done inline installs in the first place...

```
subprocess.call([sys.executable, "-m", "pip", "install", "--upgrade", "gluoncv"])
```

Is processing requirements.txt on inference startup a potential enhancement? Or an idea that's already been considered and decided against for some reason? Would it be implemented here, or in the base [sagemaker-containers](https://github.com/aws/sagemaker-containers)?

**Comment by ajaykarpur** [comment]
Hi @athewsey, this actually is supported. Details can be found here: https://sagemaker.readthedocs.io/en/stable/using_mxnet.html#use-third-party-libraries

Please feel free to re-open this issue if you run into any problems.
