### ISSUE TITLE
DEFAULT_FILENAMES hardcoded

### ISSUE THREAD

**Issue by dmadeka** [aws/sagemaker-mxnet-container#30]
Im not sure why the default file names are hardcoded, and not a member of ModuleTransformer- wouldn't it make sense to have them be parameters that are set to those values by default?

**Comment by jesterhazy** [comment]
Thanks for using SageMaker!

I assume you mean the DEFAULT_MODEL_FILENAMES defined in `train.py` [here](https://github.com/aws/sagemaker-mxnet-container/blob/master/src/mxnet_container/train.py#L26).

These filenames are used by the `default_save` method in this module, and the `default_model_fn` in the [serving code here](https://github.com/aws/sagemaker-mxnet-container/blob/master/src/mxnet_container/serve/transformer.py#L381). 

If there were parameterized, the onus would be on users to make sure they provide the same filename parameters when they create hosting endpoints. We'd also need to create a way for users to pass these parameters to their training and hosting jobs.

If you want to use different filenames, you certainly can. Just provide your own `save(mode, model_dir)` function in your training script. If you plan to create hosting endpoints, provide a compatible `model_fn(model_dir)` function in your hosting script.

Closing this ticket. Please reopen if you still have questions about this.
