### ISSUE TITLE
Bugfix to save mnist model in order to use default inference implementation

### ISSUE THREAD

**Issue by verdimrc** [aws/sagemaker-mxnet-container#61]
Hello,

to make the saved model works with the default inference implementation, I had to change  `sagemaker-mxnet-container/test/resources/keras/keras_mnist.py` line 93, from

```python
signature = [{'name': data_name, ...
```
to

```python
signature = [{'name': data_name[0], ...
```

**Reason:** `type(data_name) == list_of_string` but the default inference code expects `type(name) == str`.

Without the change, the saving logic still works, but once deployed, inference will throw exception.

**Comment by mvsusp** [comment]
Hi @verdimrc ,

Thanks for you suggestion, I created a PR with your suggested changes.

Thanks for using SageMaker!
