### ISSUE TITLE
model.deploy fails

### ISSUE THREAD

**Issue by Vikas89** [aws/sagemaker-mxnet-container#87]
I built my custom sagemaker container with https://github.com/aws/sagemaker-mxnet-container/blob/master/docker/1.4.0/final/Dockerfile.cpu 

Now I was using this script - https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/mxnet_gluon_sentiment/mxnet_sentiment_analysis_with_gluon.ipynb  

Training completes successfully but m.deploy fails complaining nginx is not there 
"No such file or directory: 'nginx'

**Comment by ChoiByungWook** [comment]
Starting with MXNet 1.4.0, the training and serving portions for images are split into these respective repos:

Training: https://github.com/aws/sagemaker-mxnet-container 
Serving: https://github.com/aws/sagemaker-mxnet-serving-container

You will need to build the serving image if you wish to use that.

For specific documentation on how to build each image please see:

Training: https://github.com/aws/sagemaker-mxnet-container#building-images
Serving: https://github.com/aws/sagemaker-mxnet-serving-container#building-images
